language: node_js
node_js:
- '8'
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm test
- npm run build
deploy:
  api_key:
    secure: FFRFrFyyMkHupliZPUDTnHGcKsy+zTUO+mRxRN8WzZMY4ILlSNfHa7wxLHnvCHaZi19ua9+XAIdQyCIatgAmQJBFjzCXZkIH6PbGyh9YthrFQN68WG0Wms3b8xX+83qxv7Y+rPK6SYIS1JSo/proE3yn2IOBZyKMZMNmTaSlAlGJIpAP/GV50Nzj93/OB5TDPK/eRxZgW8sWBoZI7Z6zkykYv/1OjKzFHW9bmTN3583TgYDJt9k18+dBQSn0pAJRHSl02fc6Jl6xVbtLaB2Cclaws+0epeSymSvl4LV3Dux3bl+Z7GQsfjjjHObsIFgxOdKofYkxBbYomSfTY/WPHe2ti69aCZbTiYAC7oXelPrbr/24BseDR4iJdjY/EXjr/XQ1yb/1lClNEH66es5SqCjjjRVEss7enjQbMema8DNkKtiHvBu6w4mtBn+KEXlfchnyuiAnK71zWibCx2k2VfwK1bTeCodRjpH/9t5OoM9bOdBI7N3xqiC9t8y1y8Aic0/lTgzl0BDcnR6ONYdHz91rD5om8RMfm1fI5PLiUx4bczfupR/nkoxCrxkH7mEz64FHLpBOTMRPUbeWvsR3kYZBvDOcDa5Zw8cr5noXo86hgJCvELED9WX4P4oPZQDBWw/Ts0MXq70rywJZJti9ZJDXyEoXuWSH7w9S4zZRORA=
  provider: heroku
  app: build-and-deploy
  skip_cleanup: true
